/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-11-05 04:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>About Us</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hp.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div style=\"font-size:140%;font-family:Comic Sans MS;\">\r\n");
      out.write("<header>\r\n");
      out.write("<section><a href=\"homepage.jsp\"><img src=\"h.png\"></a></section><h1>About Us</h1>\r\n");
      out.write("</header>\r\n");
      out.write("Communication is very much essential and the importance of it is increasing from time to time along with the evolution of \r\n");
      out.write("human needs. The purpose of conference alert  system is to provide a platform for the users to view the information about \r\n");
      out.write("the conferences that took place in the past and the ones which are about to take place in the near future. The users  can \r\n");
      out.write("first login into the system and see through the information such as details about the conferences like topic of the \r\n");
      out.write("conference, its time, venue etc. The  admin  can login and update the information ,delete any unwanted data ,arrange the \r\n");
      out.write("information accordingly so that the user can go through an user friendly and know all the whereabouts of the upcoming \r\n");
      out.write("conferences.<br/>\r\n");
      out.write("\r\n");
      out.write("</br>Normally in Telephone Conference, there will be more than two users connected at a time and all the users have to\r\n");
      out.write(" be present at the same time but this may not be possible  sometimes since they did not know about the  conferences. \r\n");
      out.write("So by implementing this system ,email alerts will be send to the people to let them know about the conference earlier so\r\n");
      out.write(" that they are able to attend and be prepared for it.<br/>\r\n");
      out.write("This system is to develop in a client/server environment.\r\n");
      out.write("The system will select the particular number of people and send e-mail alerts to them which let them know about the upcoming conferences and all the details about it. In that case to participate in any important conference or to conduct any conference will be become very easy.\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("<br/>\r\n");
      out.write("<footer>\r\n");
      out.write("Conference Hub\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
