/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2017-04-11 08:02:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addConference2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Minor_Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Conference_hub/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1478317710279L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hp.css\"/>\r\n");
      out.write("<title>Add Conference</title>\r\n");
      out.write("<script src=\"addconference.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("background-image:url(\"bg5.jpg\");\r\n");
      out.write("background-size:120%;\r\n");
      out.write("}\r\n");
      out.write("</style>  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div style=\"font-size:140%;font-family:Comic Sans MS;\">\r\n");
      out.write("<header>\r\n");
      out.write("<section><a href=\"conference.jsp\"><img src=\"back.png\"></a></section><h1>ADD CONFERENCE</h1>\r\n");
      out.write("</header>\r\n");
      out.write("<fieldset>\r\n");
      out.write("<form action=\"addConferenceController2\" method=\"post\" name='registration' onSubmit=\"return formValidation();\">\r\n");
      out.write("<br/><br/>\r\n");
      out.write("\r\n");
      out.write("Category :<select name=\"s1\">\r\n");
      out.write("<option selected=\"\" value=\"Default\">(Please select a category)</option> \r\n");
      out.write("  <option value=\"computer software & applications\">computer software & applications</option>\r\n");
      out.write(" <option value=\"biotechnology\">biotechnology</option>\r\n");
      out.write(" <option value=\"artificial intelligence\">artificial intelligence</option>\r\n");
      out.write("<option value=\"health\">health</option>\r\n");
      out.write("<option value=\"medicine & medical science\">medicine & medical science</option>\r\n");
      out.write("<option value=\"nursing\">nursing</option>\r\n");
      out.write("<option value=\"tourism\">tourism</option>\r\n");
      out.write("<option value=\"culture\">culture</option>\r\n");
      out.write("<option value=\"globalization\">globalization</option>\r\n");
      out.write("<option value=\"marketing\">marketing</option>\r\n");
      out.write("<option value=\"management\">management</option>\r\n");
      out.write("<option value=\"e-commerce\">e-commerce</option>\r\n");
      out.write("<option value=\"null\">null</option>\r\n");
      out.write("</select><br/><br/>\r\n");
      out.write("\r\n");
      out.write("Day:<select name=\"s2\">\r\n");
      out.write("<option selected=\"\" value=\"Default\">(Please select a Day)</option> \r\n");
      out.write(" ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </select>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("Month:<select name=\"s3\">\r\n");
      out.write("<option selected=\"\" value=\"Default\">(Please select a Month)</option> \r\n");
      out.write("\r\n");
      out.write("  <option value=\"january\">january</option>\r\n");
      out.write("  <option value=\"february\">february</option>\r\n");
      out.write("  <option value=\"march\">march</option>\r\n");
      out.write("  <option value=\"april\">april</option>\r\n");
      out.write("<option value=\"may\">may</option>\r\n");
      out.write("<option value=\"june\">june</option>\r\n");
      out.write("<option value=\"july\">july</option>\r\n");
      out.write("<option value=\"august\">august</option>\r\n");
      out.write("<option value=\"september\">september</option>\r\n");
      out.write("<option value=\"october\">october</option>\r\n");
      out.write("<option value=\"november\">november</option>\r\n");
      out.write("<option value=\"december\">december</option>\r\n");
      out.write("</select>\r\n");
      out.write("Year:<select name=\"s4\">\r\n");
      out.write("<option selected=\"\" value=\"Default\">(Please select a Year)</option> \r\n");
      out.write("<option value=\"Year\">Year</option>\r\n");
      out.write("  \r\n");
      out.write("  <option value=\"2017\">2017</option>\r\n");
      out.write("  <option value=\"2018\">2018</option>\r\n");
      out.write("</select><br/><br/>\r\n");
      out.write("Title:<input type=\"text\" placeholder=\"Enter Title\" name=\"t1\" /><br/><br/>\r\n");
      out.write("Venue:<input type=\"text\" placeholder=\"Enter Venue\" name=\"t2\" /><br/><br/>\r\n");
      out.write("Type Of Category<select name=\"s5\">\r\n");
      out.write("<option selected=\"\" value=\"Default\">(Please select a Type)</option>\r\n");
      out.write("\r\n");
      out.write("  <option value=\"National\">National</option>\r\n");
      out.write("  <option value=\"Inter-National\">Inter-National</option>\r\n");
      out.write("  </select><br/><br/>\r\n");
      out.write("<input type=\"submit\" value=\"Add to database\"/>\r\n");
      out.write("<input type=\"reset\" value=\"Reset\">\r\n");
      out.write("</form>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("<footer>\r\n");
      out.write("Conference Hub\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /addConference2.jsp(46,1) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(1);
    // /addConference2.jsp(46,1) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(31);
    // /addConference2.jsp(46,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("day");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write(" \t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
