/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2017-04-11 08:25:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hp.css\"/>\r\n");
      out.write("<link rel=\"icon\" href=\"logo.png\" type=\"logo.png\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("a:hover{\r\n");
      out.write(" \tcolor: red;\r\n");
      out.write("    background-color:transparent;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}</style>\r\n");
      out.write("<title>Conference Hub</title>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("background-image:url(\"OpenCongress.jpg\");\r\n");
      out.write("background-size:150%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"hp.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<font face=\"comic sans ms\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"myNav\" class=\"overlay\">\r\n");
      out.write(" <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">X</a>\r\n");
      out.write("  <div class=\"overlay-content\">\r\n");
      out.write("    <a href=\"aboutus.jsp\">About</a>\r\n");
      out.write("    <a href=\"subscribe.jsp\">Subscribe</a>\r\n");
      out.write("    <a href=\"sign.jsp\">Sign In</a>\r\n");
      out.write("  <a href=\"imghub.jsp\">Image Hub</a>\r\n");
      out.write("   <a href=\"videohub.jsp\">Video Hub\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"contact.jsp\">Contact</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<header><h1>Conference Hub</h1>\r\n");
      out.write("</header>\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<marquee behaviour=\"slide\" direction=\"right\" scrolldelay=0 height=\"300\"><img src=\"0.jpg\"><img src=\"1.jpg\"><img src=\"3.jpg\"><img src=\"4.jpg\"><img src=\"6.jpg\"><img src=\"7.jpg\"><img src=\"8.jpg\"><img src=\"9.jpg\"><img src=\"10.jpg\"><img src=\"11.jpg\"><img src=\"12.jpg\">\r\n");
      out.write("</marquee><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("<a><span style=\"font-size:40px;cursor:pointer\" onclick=\"openNav()\"><center><font size=\"12\" face=\"comic sans ms\"><b>Go to Hub</b></font></center></span></a>\r\n");
      out.write("<br/><br/><br/><br/><br/><br/>\r\n");
      out.write("<br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("\r\n");
      out.write("<center><p><font size=20px color=\"cornsilk\" face=\"vivaldi\"> It let's you explore all the upcoming conferences round the globe.<br/>\r\n");
      out.write("Know all the latest trends in your field and be the lead...</center></p></font>\r\n");
      out.write("\r\n");
      out.write("<br/><br/><br/><br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2 align=\"right\"><font color=\"crimson\">FOLLOW US ON :</font></h2>\r\n");
      out.write("<img src=\"f.png\" align=\"right\"><img src=\"g.png\" align=\"right\"><img src=\"y.png\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("@Copyright 2016 Conference Alerts</footer>\r\n");
      out.write("</font>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
